### ISSUE TITLE
File system rights leads to invalid patch

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/utils.patcher#1]
When a file could not be created, the patch might be still created.

Then, it is not possible to change the real path of the patch file, and therefore the patch will never be runnable unless the final file matches the one referered in MoufComponents

**Comment by moufmouf** [comment]
I cannot reproduce the bug.
I tried to:
1- set the database/up directory to "not writable"
2- create a new database patch

I'm getting a nice warning message: "Sorry, directory '/home/david/projects/mouf/mouf2/database/up' is not writable. Please check directory permissions."
Finally, the patch instance is not created.

Any idea on how to reproduce?

**Comment by moufmouf** [comment]
Old issue, not reproduced. I'm closing this.
